[package]
name = "bevy_pigeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0", features = ["bevy_dylib"] }
carrier-pigeon = "0.2.0"
serde = { version = "~1.0", features = ["derive"] }
heron = { version = "3.0", features = ["2d"] }

[profile.dev.package."*"]
opt-level = 3
